spring:
  application:
    name: winter-front
server:
  port: 7211

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  #password: password
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.128.164.245:3300/eureka/
#      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

## 日志管理控制
debug: false
logging:
  path: /tmp/winter
  file: /tmp/winter/${spring.application.name}.log
  level:
    root: INFO
    cn.letcode: DEBUG
    org.springframework.web: WARN
    org.hibernate: ERROR