spring:
  application:
    name: winter-front
server:
  port: 7211

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:3300/eureka/
#      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

## 日志管理控制
debug: false
logging:
  path: /tmp/winter
  file: /tmp/winter/${spring.application.name}.log
  level:
    root: INFO
    cn.letcode: DEBUG
    org.springframework.web: WARN
    org.hibernate: ERROR