package cn.letcode.winter.webmagic.mapper;

import cn.letcode.winter.webmagic.model.DoubleColorBall;

public interface DoubleColorBallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    int insert(DoubleColorBall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    int insertSelective(DoubleColorBall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    DoubleColorBall selectByPrimaryKey(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    DoubleColorBall selectByMaxKey();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DoubleColorBall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DoubleColorBall record);
}