server:
    port: 58001
spring:
    application:
        name: winter-webmagic

    datasource:
        name: prod
#        url: jdbc:mysql://localhost:3306/winterdb?useUnicode=true&characterEncoding=utf8
        url: jdbc:mysql://10.128.164.245:3306/winterdb?useUnicode=true&characterEncoding=utf8
        username: winter
        password: winter123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    mail:
        host: smtp.letcode.cn
        # port: 465
        username: service@letcode.cn
        password: 你的密码
        properties:
            mail:
                smtp:
                    auth: true
                socketFactory:
                      port: 465
                      class: javax.net.ssl.SSLSocketFactory
                      fallback: false
                self:
                    username: service@letcode.cn

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: cn.letcode.winter.webmagic.model

mapper:
    mappers: cn.letcode.winter.webmagic.mapper
    not-empty: false
    identity: MYSQL



## 日志管理控制
debug: false
logging:
    file: /tmp/logs/${spring.application.name}.log
#    file: ../logs/${spring.application.name}.log
    level:
        root: INFO
        cn.letcode: INFO
        org.springframework.web: WARN
        org.hibernate: ERROR

## 自定义系统参数
global:
    schedule:
#        doubleColorBallCron: "0 0 1 * * ?"
        doubleColorBallCron: "*/5 * * * * ?"
