server:
  port: 3300
spring:
  application:
    name: winter-eureka-server
eureka:
  server:
    # 关闭自我保护模式（缺省为打开）
    enable-self-preservation: true
    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）
      registry-fetch-interval-seconds: 5      # 默认为30秒
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:3300/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}




