server:
    port: 3300
spring:
    application:
        name: winter-eureka-server
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:3300/eureka/
    instance:
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}