package cn.letcode.winter.webmagic.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class DoubleColorBall implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.issue_no
     *
     * @mbggenerated
     */
    private String issueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.issue_date
     *
     * @mbggenerated
     */
    private String issueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.redball1
     *
     * @mbggenerated
     */
    private String redball1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.redball2
     *
     * @mbggenerated
     */
    private String redball2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.redball3
     *
     * @mbggenerated
     */
    private String redball3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.redball4
     *
     * @mbggenerated
     */
    private String redball4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.redball5
     *
     * @mbggenerated
     */
    private String redball5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.redball6
     *
     * @mbggenerated
     */
    private String redball6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.blueball1
     *
     * @mbggenerated
     */
    private String blueball1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.blueball2
     *
     * @mbggenerated
     */
    private String blueball2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.sell_amt
     *
     * @mbggenerated
     */
    private BigDecimal sellAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.first_prize
     *
     * @mbggenerated
     */
    private BigDecimal firstPrize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_double_color_ball.prize_pool
     *
     * @mbggenerated
     */
    private BigDecimal prizePool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.id
     *
     * @return the value of w_double_color_ball.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.id
     *
     * @param id the value for w_double_color_ball.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.issue_no
     *
     * @return the value of w_double_color_ball.issue_no
     *
     * @mbggenerated
     */
    public String getIssueNo() {
        return issueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.issue_no
     *
     * @param issueNo the value for w_double_color_ball.issue_no
     *
     * @mbggenerated
     */
    public void setIssueNo(String issueNo) {
        this.issueNo = issueNo == null ? null : issueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.issue_date
     *
     * @return the value of w_double_color_ball.issue_date
     *
     * @mbggenerated
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.issue_date
     *
     * @param issueDate the value for w_double_color_ball.issue_date
     *
     * @mbggenerated
     */
    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate == null ? null : issueDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.redball1
     *
     * @return the value of w_double_color_ball.redball1
     *
     * @mbggenerated
     */
    public String getRedball1() {
        return redball1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.redball1
     *
     * @param redball1 the value for w_double_color_ball.redball1
     *
     * @mbggenerated
     */
    public void setRedball1(String redball1) {
        this.redball1 = redball1 == null ? null : redball1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.redball2
     *
     * @return the value of w_double_color_ball.redball2
     *
     * @mbggenerated
     */
    public String getRedball2() {
        return redball2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.redball2
     *
     * @param redball2 the value for w_double_color_ball.redball2
     *
     * @mbggenerated
     */
    public void setRedball2(String redball2) {
        this.redball2 = redball2 == null ? null : redball2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.redball3
     *
     * @return the value of w_double_color_ball.redball3
     *
     * @mbggenerated
     */
    public String getRedball3() {
        return redball3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.redball3
     *
     * @param redball3 the value for w_double_color_ball.redball3
     *
     * @mbggenerated
     */
    public void setRedball3(String redball3) {
        this.redball3 = redball3 == null ? null : redball3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.redball4
     *
     * @return the value of w_double_color_ball.redball4
     *
     * @mbggenerated
     */
    public String getRedball4() {
        return redball4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.redball4
     *
     * @param redball4 the value for w_double_color_ball.redball4
     *
     * @mbggenerated
     */
    public void setRedball4(String redball4) {
        this.redball4 = redball4 == null ? null : redball4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.redball5
     *
     * @return the value of w_double_color_ball.redball5
     *
     * @mbggenerated
     */
    public String getRedball5() {
        return redball5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.redball5
     *
     * @param redball5 the value for w_double_color_ball.redball5
     *
     * @mbggenerated
     */
    public void setRedball5(String redball5) {
        this.redball5 = redball5 == null ? null : redball5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.redball6
     *
     * @return the value of w_double_color_ball.redball6
     *
     * @mbggenerated
     */
    public String getRedball6() {
        return redball6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.redball6
     *
     * @param redball6 the value for w_double_color_ball.redball6
     *
     * @mbggenerated
     */
    public void setRedball6(String redball6) {
        this.redball6 = redball6 == null ? null : redball6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.blueball1
     *
     * @return the value of w_double_color_ball.blueball1
     *
     * @mbggenerated
     */
    public String getBlueball1() {
        return blueball1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.blueball1
     *
     * @param blueball1 the value for w_double_color_ball.blueball1
     *
     * @mbggenerated
     */
    public void setBlueball1(String blueball1) {
        this.blueball1 = blueball1 == null ? null : blueball1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.blueball2
     *
     * @return the value of w_double_color_ball.blueball2
     *
     * @mbggenerated
     */
    public String getBlueball2() {
        return blueball2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.blueball2
     *
     * @param blueball2 the value for w_double_color_ball.blueball2
     *
     * @mbggenerated
     */
    public void setBlueball2(String blueball2) {
        this.blueball2 = blueball2 == null ? null : blueball2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.sell_amt
     *
     * @return the value of w_double_color_ball.sell_amt
     *
     * @mbggenerated
     */
    public BigDecimal getSellAmt() {
        return sellAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.sell_amt
     *
     * @param sellAmt the value for w_double_color_ball.sell_amt
     *
     * @mbggenerated
     */
    public void setSellAmt(BigDecimal sellAmt) {
        this.sellAmt = sellAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.first_prize
     *
     * @return the value of w_double_color_ball.first_prize
     *
     * @mbggenerated
     */
    public BigDecimal getFirstPrize() {
        return firstPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.first_prize
     *
     * @param firstPrize the value for w_double_color_ball.first_prize
     *
     * @mbggenerated
     */
    public void setFirstPrize(BigDecimal firstPrize) {
        this.firstPrize = firstPrize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_double_color_ball.prize_pool
     *
     * @return the value of w_double_color_ball.prize_pool
     *
     * @mbggenerated
     */
    public BigDecimal getPrizePool() {
        return prizePool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_double_color_ball.prize_pool
     *
     * @param prizePool the value for w_double_color_ball.prize_pool
     *
     * @mbggenerated
     */
    public void setPrizePool(BigDecimal prizePool) {
        this.prizePool = prizePool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DoubleColorBall other = (DoubleColorBall) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIssueNo() == null ? other.getIssueNo() == null : this.getIssueNo().equals(other.getIssueNo()))
            && (this.getIssueDate() == null ? other.getIssueDate() == null : this.getIssueDate().equals(other.getIssueDate()))
            && (this.getRedball1() == null ? other.getRedball1() == null : this.getRedball1().equals(other.getRedball1()))
            && (this.getRedball2() == null ? other.getRedball2() == null : this.getRedball2().equals(other.getRedball2()))
            && (this.getRedball3() == null ? other.getRedball3() == null : this.getRedball3().equals(other.getRedball3()))
            && (this.getRedball4() == null ? other.getRedball4() == null : this.getRedball4().equals(other.getRedball4()))
            && (this.getRedball5() == null ? other.getRedball5() == null : this.getRedball5().equals(other.getRedball5()))
            && (this.getRedball6() == null ? other.getRedball6() == null : this.getRedball6().equals(other.getRedball6()))
            && (this.getBlueball1() == null ? other.getBlueball1() == null : this.getBlueball1().equals(other.getBlueball1()))
            && (this.getBlueball2() == null ? other.getBlueball2() == null : this.getBlueball2().equals(other.getBlueball2()))
            && (this.getSellAmt() == null ? other.getSellAmt() == null : this.getSellAmt().equals(other.getSellAmt()))
            && (this.getFirstPrize() == null ? other.getFirstPrize() == null : this.getFirstPrize().equals(other.getFirstPrize()))
            && (this.getPrizePool() == null ? other.getPrizePool() == null : this.getPrizePool().equals(other.getPrizePool()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIssueNo() == null) ? 0 : getIssueNo().hashCode());
        result = prime * result + ((getIssueDate() == null) ? 0 : getIssueDate().hashCode());
        result = prime * result + ((getRedball1() == null) ? 0 : getRedball1().hashCode());
        result = prime * result + ((getRedball2() == null) ? 0 : getRedball2().hashCode());
        result = prime * result + ((getRedball3() == null) ? 0 : getRedball3().hashCode());
        result = prime * result + ((getRedball4() == null) ? 0 : getRedball4().hashCode());
        result = prime * result + ((getRedball5() == null) ? 0 : getRedball5().hashCode());
        result = prime * result + ((getRedball6() == null) ? 0 : getRedball6().hashCode());
        result = prime * result + ((getBlueball1() == null) ? 0 : getBlueball1().hashCode());
        result = prime * result + ((getBlueball2() == null) ? 0 : getBlueball2().hashCode());
        result = prime * result + ((getSellAmt() == null) ? 0 : getSellAmt().hashCode());
        result = prime * result + ((getFirstPrize() == null) ? 0 : getFirstPrize().hashCode());
        result = prime * result + ((getPrizePool() == null) ? 0 : getPrizePool().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_double_color_ball
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", issueNo=").append(issueNo);
        sb.append(", issueDate=").append(issueDate);
        sb.append(", redball1=").append(redball1);
        sb.append(", redball2=").append(redball2);
        sb.append(", redball3=").append(redball3);
        sb.append(", redball4=").append(redball4);
        sb.append(", redball5=").append(redball5);
        sb.append(", redball6=").append(redball6);
        sb.append(", blueball1=").append(blueball1);
        sb.append(", blueball2=").append(blueball2);
        sb.append(", sellAmt=").append(sellAmt);
        sb.append(", firstPrize=").append(firstPrize);
        sb.append(", prizePool=").append(prizePool);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}